### ISSUE TITLE
Hardaware question. 5v sensor interfacing via uart with the 3.3v of ESP32

### ISSUE THREAD

**Issue by cma1100b** [DuncanIdahoCT/espresence-mr60bha1-mmwave-sensor#1]
Hi, this isnt a issue by it self as it is more a question about the hardware level specifics.

I am trying to integrate multiple sensors into a esp32/esphome environment. However there is a problem with the power levels of the diferent devices. 
Esp32 works with 3.3v and the MR60BHA1 wirks with 5v. I am nor concerned with the power requirements as my input is based on the power rails of the esp32's usb. Th problem comes with the uart conection. 

What did you use to interface them, a level shifter (that is the only thing that i could think would solve the problem). I am a almost complete noob with this kinds of thing so the help is gratelly apreciated.
Thank you very much.

**Comment by DuncanIdahoCT** [comment]
Hi, yes some ESP MCUs have only a 3.3v rail but many of them have both a 5v and 3.3 these are the ones I tend to use since some modules require 5.0v and some will allow less or require 3.3. The ESP dev boards in these cases do the voltage transformation for you, you give them full USB 5v and they have a 3.3v pad you can use. The specific ESP32 and ESP8266 boards I've purchased and even the fingertip sized AdafruitESP MCUs I've used all have 5 and 3.3v pins/pads.

![image](https://github.com/DuncanIdahoCT/espresence-mr60bha1-mmwave-sensor/assets/18145071/f189e8e0-0662-490d-861b-8c0e1c15fc45)

**Comment by cma1100b** [comment]
Hello.
I tested this, however the ESP32C3 that i am using can tolerate 5v but it works best with 3v3, so i considered using level shifters. However as the sensor detects the 3v3 signals as logical 1 either way we setled on using a voltage divider on the tx pin of the sensor. 
Thank you very much for replying.
